/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  DataResponseAlbumItemResponsePublic,
  PageAlbumItemResponsePublic
} from '../../schemas'

export const getGetPubAlbumsGetResponseMock = (overrideResponse: Partial< PageAlbumItemResponsePublic > = {}): PageAlbumItemResponsePublic => ({code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), data: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({album_image_price: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), album_image_url: faker.string.alpha(20), album_name: faker.string.alpha(20), album_price: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), album_slug: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), event_date: `${faker.date.past().toISOString().split('.')[0]}Z`, id: faker.number.int({min: undefined, max: undefined}), is_album_free: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), is_find_all_image: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), is_highlight: faker.number.int({min: undefined, max: undefined}), total_image: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined])})), message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), metadata: {current_page: faker.number.int({min: undefined, max: undefined}), page_size: faker.number.int({min: undefined, max: undefined}), total_items: faker.number.int({min: undefined, max: undefined})}, ...overrideResponse})

export const getDetailPubAlbumsAlbumSlugGetResponseMock = (overrideResponse: Partial< DataResponseAlbumItemResponsePublic > = {}): DataResponseAlbumItemResponsePublic => ({code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), data: faker.helpers.arrayElement([{album_image_price: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), album_image_url: faker.string.alpha(20), album_name: faker.string.alpha(20), album_price: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), album_slug: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), event_date: `${faker.date.past().toISOString().split('.')[0]}Z`, id: faker.number.int({min: undefined, max: undefined}), is_album_free: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), is_find_all_image: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), is_highlight: faker.number.int({min: undefined, max: undefined}), total_image: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined])}, undefined]), message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), ...overrideResponse})


export const getGetPubAlbumsGetMockHandler = (overrideResponse?: PageAlbumItemResponsePublic | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PageAlbumItemResponsePublic> | PageAlbumItemResponsePublic)) => {
  return http.get('*/pub/albums', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetPubAlbumsGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getDetailPubAlbumsAlbumSlugGetMockHandler = (overrideResponse?: DataResponseAlbumItemResponsePublic | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DataResponseAlbumItemResponsePublic> | DataResponseAlbumItemResponsePublic)) => {
  return http.get('*/pub/albums/:albumSlug', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getDetailPubAlbumsAlbumSlugGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGenCertificateThumbnailImagePubAlbumsGenCertificateThumbnailImagePostMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<unknown> | unknown)) => {
  return http.post('*/pub/albums/gen-certificate-thumbnail-image', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}
export const getPublicAlbumMock = () => [
  getGetPubAlbumsGetMockHandler(),
  getDetailPubAlbumsAlbumSlugGetMockHandler(),
  getGenCertificateThumbnailImagePubAlbumsGenCertificateThumbnailImagePostMockHandler()
]
