version: '3.8'

services:
  web:
    image: anhnd39/5pix:1.3.41
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Add healthcheck to ensure the application is running properly
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3
