/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  DataResponseAlbumImageItemResponsePublic,
  PageAlbumImageItemResponsePublic
} from '../../schemas'

export const getSearchPubImagesPostResponseMock = (overrideResponse: Partial< PageAlbumImageItemResponsePublic > = {}): PageAlbumImageItemResponsePublic => ({code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), data: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({cdn_image_url: faker.string.alpha(20), id: faker.number.int({min: undefined, max: undefined}), image_name: faker.string.alpha(20), s3_image_url: faker.helpers.arrayElement([faker.string.alpha(20), undefined])})), message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), metadata: {current_page: faker.number.int({min: undefined, max: undefined}), page_size: faker.number.int({min: undefined, max: undefined}), total_items: faker.number.int({min: undefined, max: undefined})}, ...overrideResponse})

export const getDetailImagePubImagesImageIdGetResponseMock = (overrideResponse: Partial< DataResponseAlbumImageItemResponsePublic > = {}): DataResponseAlbumImageItemResponsePublic => ({code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), data: faker.helpers.arrayElement([{cdn_image_url: faker.string.alpha(20), id: faker.number.int({min: undefined, max: undefined}), image_name: faker.string.alpha(20), s3_image_url: faker.helpers.arrayElement([faker.string.alpha(20), undefined])}, undefined]), message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), ...overrideResponse})


export const getSearchPubImagesPostMockHandler = (overrideResponse?: PageAlbumImageItemResponsePublic | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PageAlbumImageItemResponsePublic> | PageAlbumImageItemResponsePublic)) => {
  return http.post('*/pub/images', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getSearchPubImagesPostResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getDetailImagePubImagesImageIdGetMockHandler = (overrideResponse?: DataResponseAlbumImageItemResponsePublic | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DataResponseAlbumImageItemResponsePublic> | DataResponseAlbumImageItemResponsePublic)) => {
  return http.get('*/pub/images/:imageId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getDetailImagePubImagesImageIdGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getPublicImagesMock = () => [
  getSearchPubImagesPostMockHandler(),
  getDetailImagePubImagesImageIdGetMockHandler()
]
