/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 *
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize

 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from '@tanstack/react-query'
import type { MutationFunction, UseMutationOptions, UseMutationResult } from '@tanstack/react-query'
import axios from 'axios'
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios'
import type {
  BodySearchPubImagesPost,
  HTTPValidationError,
  PageAlbumImageItemResponsePublic,
  SearchPubImagesPostParams,
} from '../../schemas'

/**
 * API Search Album Image
 * @summary Search
 */
export const searchPubImagesPost = (
  bodySearchPubImagesPost: BodySearchPubImagesPost,
  params?: SearchPubImagesPostParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<PageAlbumImageItemResponsePublic>> => {
  const formData = new FormData()
  if (bodySearchPubImagesPost.avatar_file !== undefined) {
    formData.append('avatar_file', bodySearchPubImagesPost.avatar_file)
  }

  return axios.post(`https://dapi.5pix.org/pub/images`, formData, {
    ...options,
    params: { ...params, ...options?.params },
  })
}

export const getSearchPubImagesPostMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof searchPubImagesPost>>,
    TError,
    { data: BodySearchPubImagesPost; params?: SearchPubImagesPostParams },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof searchPubImagesPost>>,
  TError,
  { data: BodySearchPubImagesPost; params?: SearchPubImagesPostParams },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof searchPubImagesPost>>,
    { data: BodySearchPubImagesPost; params?: SearchPubImagesPostParams }
  > = (props) => {
    const { data, params } = props ?? {}

    return searchPubImagesPost(data, params, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type SearchPubImagesPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof searchPubImagesPost>>
>
export type SearchPubImagesPostMutationBody = BodySearchPubImagesPost
export type SearchPubImagesPostMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Search
 */
export const useSearchPubImagesPost = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof searchPubImagesPost>>,
    TError,
    { data: BodySearchPubImagesPost; params?: SearchPubImagesPostParams },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationResult<
  Awaited<ReturnType<typeof searchPubImagesPost>>,
  TError,
  { data: BodySearchPubImagesPost; params?: SearchPubImagesPostParams },
  TContext
> => {
  const mutationOptions = getSearchPubImagesPostMutationOptions(options)

  return useMutation(mutationOptions)
}
