/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */
import type { ImageQueryDTO } from './imageQueryDTO';

export interface AddImageResponse {
  album_id?: number;
  album_images_id?: number[];
  album_name?: string;
  collection_item_ids?: number[];
  id?: number;
  name?: string;
  order_id?: number;
  owner_id?: number;
  queries?: ImageQueryDTO[];
}
