/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */

/**
 * An enumeration.
 */
export type AlbumImageIndexStatus = typeof AlbumImageIndexStatus[keyof typeof AlbumImageIndexStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlbumImageIndexStatus = {
  saved_to_s3: 'saved_to_s3',
  indexing: 'indexing',
  index_complete: 'index_complete',
} as const;
