/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */

/**
 * An enumeration.
 */
export type AlbumLinkKeywordType = typeof AlbumLinkKeywordType[keyof typeof AlbumLinkKeywordType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlbumLinkKeywordType = {
  bib_number: 'bib_number',
  image_name: 'image_name',
} as const;
