/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */
import type { CollectionImageWithQueryResponseByImgQueriesAlbumImages } from './collectionImageWithQueryResponseByImgQueriesAlbumImages';
import type { CollectionImageWithQueryResponseImageQueries } from './collectionImageWithQueryResponseImageQueries';
import type { ItemResponse } from './itemResponse';

export interface CollectionImageWithQueryResponse {
  by_img_queries_album_images?: CollectionImageWithQueryResponseByImgQueriesAlbumImages;
  image_queries?: CollectionImageWithQueryResponseImageQueries;
  images?: ItemResponse[];
}
