/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */
import type { ImageQueryDTO } from './imageQueryDTO';
import type { OrderInternalStatus } from './orderInternalStatus';

export interface CollectionImageResponse {
  album_id?: number;
  album_image_price?: number;
  album_name?: string;
  album_price?: number;
  album_slug?: string;
  estimate_price?: number;
  id: number;
  image_queries?: ImageQueryDTO[];
  name: string;
  order_id?: number;
  order_internal_status?: OrderInternalStatus;
  owner_id: number;
  query_keyword?: string;
  query_type?: string;
}
