/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */
import type { OrderCategory } from './orderCategory';
import type { OrderInternalStatus } from './orderInternalStatus';
import type { LineResponse } from './lineResponse';

export interface CreateOrderResponse {
  category?: OrderCategory;
  id?: number;
  internal_status?: OrderInternalStatus;
  line_items?: LineResponse[];
  name?: string;
  owner_email?: string;
}
