/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */
import type { MerchantItemResponse } from './merchantItemResponse';

export interface DataResponseMerchantItemResponse {
  code?: string;
  data?: MerchantItemResponse;
  message?: string;
}
