/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */

/**
 * Generic enumeration.

    Derive from this class to define new enumerations.

    
 */
export type Enum = typeof Enum[keyof typeof Enum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Enum = {
} as const;
