/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */
import type { Album5pixStatus } from './album5pixStatus';

export type GetAlbumsGetParams = {
highlight?: boolean;
album_5pix_status?: Album5pixStatus;
album_display_status?: number;
is_album_free?: number;
page_size?: number;
page?: number;
sort_by?: string;
order?: string;
};
