/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */

/**
 * An enumeration.
 */
export type ImageSearchType = (typeof ImageSearchType)[keyof typeof ImageSearchType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImageSearchType = {
  all: 'all',
  metadata: 'metadata',
  index_face: 'index_face',
} as const
