/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */

export interface ItemResponse {
  album_id?: number;
  album_image_id?: number;
  album_image_name?: string;
  album_image_url?: string;
  album_name?: string;
  collection_name?: string;
  id: number;
  name?: string;
  order_id?: number;
  owner_id?: number;
}
