/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */

/**
 * An enumeration.
 */
export type MerchantYearsOfExperience = typeof MerchantYearsOfExperience[keyof typeof MerchantYearsOfExperience];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MerchantYearsOfExperience = {
  '<_1': '< 1',
  '1-3': '1-3',
  '3-5': '3-5',
  '>_5': '> 5',
} as const;
