/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */

/**
 * An enumeration.
 */
export type MerchantApprovedStatus = typeof MerchantApprovedStatus[keyof typeof MerchantApprovedStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MerchantApprovedStatus = {
  approved: 'approved',
  waiting_for_approve: 'waiting_for_approve',
  rejected: 'rejected',
} as const;
