/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */
import type { Enum } from './enum'

export interface MerchantDetailResponse {
  address: string
  date_of_birth?: string
  email: string
  events_attended?: string
  full_name?: string
  id: number
  merchant_active_status?: Enum
  merchant_active_status_note?: string
  merchant_type: string
  phone_number: string
  sample_photo_link?: string
  social_media_link?: string
  years_of_experience?: string
}
