/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */
import type { Enum } from './enum';

export interface MerchantItemResponse {
  address: string;
  email: string;
  full_name?: string;
  id: number;
  merchant_active_status?: Enum;
  merchant_type: Enum;
  phone_number: string;
}
