/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */
import type { MerchantApprovedStatus } from './merchantApprovedStatus';

export interface MerchantApproveRequest {
  merchant_active_status: MerchantApprovedStatus;
  merchant_active_status_note?: string;
  merchant_id: number;
}
