/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */

/**
 * An enumeration.
 */
export type OrderInternalStatus = typeof OrderInternalStatus[keyof typeof OrderInternalStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderInternalStatus = {
  NEW: 'NEW',
  WAIT_FOR_PAYMENT: 'WAIT_FOR_PAYMENT',
  PROCESSING: 'PROCESSING',
  PAY_GATE_FAIL: 'PAY_GATE_FAIL',
  COMPLETE: 'COMPLETE',
  CANCELLED: 'CANCELLED',
} as const;
