/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */
import type { CreditLogResponse } from './creditLogResponse';
import type { MetadataSchema } from './metadataSchema';

export interface PageCreditLogResponse {
  code?: string;
  data: CreditLogResponse[];
  message?: string;
  metadata: MetadataSchema;
}
