/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */

import { UserRole } from './userRole'

export interface UserItemResponse {
  id: number
  email: string
  full_name?: string
  created_at?: string
  role: keyof typeof UserRole
}
