/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 5PIX BACKEND PROD
 * 
        Base frame with FastAPI micro framework + Postgresql
            - Login/Register with JWT
            - Permission
            - CRUD User
            - Unit testing with Pytest
            - Dockerize
        
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'
import type {
  DataResponseToken,
  HTTPValidationError,
  LoginRequest
} from '../../schemas'
import { defaultMutator } from '../../api/axiosInstance';



/**
 * @summary Login Access Token
 */
export const loginAccessTokenLoginPost = (
    loginRequest: LoginRequest,
 signal?: AbortSignal
) => {
      
      
      return defaultMutator<DataResponseToken>(
      {url: `/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      );
    }
  


export const getLoginAccessTokenLoginPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAccessTokenLoginPost>>, TError,{data: LoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof loginAccessTokenLoginPost>>, TError,{data: LoginRequest}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginAccessTokenLoginPost>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginAccessTokenLoginPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginAccessTokenLoginPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginAccessTokenLoginPost>>>
    export type LoginAccessTokenLoginPostMutationBody = LoginRequest
    export type LoginAccessTokenLoginPostMutationError = HTTPValidationError

    /**
 * @summary Login Access Token
 */
export const useLoginAccessTokenLoginPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAccessTokenLoginPost>>, TError,{data: LoginRequest}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof loginAccessTokenLoginPost>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getLoginAccessTokenLoginPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    