name: Auto bump patch version and push Docker image

on:
  push:
    branches:
      - master
      - dev

jobs:
  bump-version-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current version
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Get current environment
        id: get_env
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "NEXT_PUBLIC_ENV=prod" >> $GITHUB_ENV
          else
            echo "NEXT_PUBLIC_ENV=development" >> $GITHUB_ENV
          fi

      - name: Get current version master
        if: github.ref == 'refs/heads/master'
        id: get_version_master
        run: echo "NEW_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Bump patch version
        if: github.ref != 'refs/heads/master'
        id: bump_patch
        run: |
          IFS='.' read -r major minor patch <<< "$VERSION"
          patch=$((patch+1))
          new_version="$major.$minor.$patch"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
          echo "$new_version" > VERSION
      - name: Update docker-compose.yml image version
        if: github.ref != 'refs/heads/master'
        run: |
          sed -i "s|image: anhnd39/5pix-${NODE_ENV}:.*|image: anhnd39/5pix-${NODE_ENV}:${{ env.NEW_VERSION }}|" docker-compose.yml

      - name: Commit and push updated VERSION and docker-compose.yml
        if: github.ref != 'refs/heads/master'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: 'chore: bump version to ${{ env.NEW_VERSION }}'
          add: |
            VERSION
            docker-compose.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup environment variables
        run: |
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.local
          echo ${{ env.NEXT_PUBLIC_ENV }} > .env.local
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "GOOGLE_ID=${{ secrets.GOOGLE_ID }}" >> .env.local
            echo "GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }}" >> .env.local
            echo "NEXTAUTH_URL=https://5pix.org/" >> .env.local
            echo "NEXT_PUBLIC_API_BASE_URL=https://api.5pix.org" >> .env.local
          else
            echo "GOOGLE_ID=${{ secrets.GOOGLE_ID_DEV }}" >> .env.local
            echo "GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET_DEV }}" >> .env.local
            echo "NEXTAUTH_URL=https://fe-dev.5pix.org/" >> .env.local
            echo "NEXT_PUBLIC_API_BASE_URL=https://dapi.5pix.org" >> .env.local
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/5pix-${{ env.NEXT_PUBLIC_ENV}}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/5pix-${{env.NEXT_PUBLIC_ENV}}:${{ env.NEW_VERSION }}
